# deployment-blue.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app-blue # Unique name for the blue deployment
  labels:
    app: python-app
    version: blue # Label to identify this as the blue version
spec:
  replicas: 4 # Number of replicas for your blue environment
  selector:
    matchLabels:
      app: python-app
      version: blue # Selector must match the pod labels
  template:
    metadata:
      labels:
        app: python-app
        version: blue # Pods created by this deployment will have the 'blue' label
    spec:
      containers:
      - name: python-app
        image: jyotsnayadagiri/python-ci:v1 # Current production image
        ports:
        - containerPort: 5000
