apiVersion: apps/v1
kind: Deployment
metadata:
  # Harness will dynamically name this, e.g., python-app-blue or python-app-green
  name: python-app-{{ .Values.versionLabel }}
  labels:
    app: python-app
    version: {{ .Values.versionLabel }} # Dynamic label for blue or green
spec:
  replicas: 4 # Number of replicas for your environment
  selector:
    matchLabels:
      app: python-app
      version: {{ .Values.versionLabel }} # Selector must match the dynamic pod labels
  template:
    metadata:
      labels:
        app: python-app
        version: {{ .Values.versionLabel }} # Pods created by this deployment will have the dynamic label
    spec:
      containers:
      - name: python-app
        image: {{ .Values.image }} # Image will be injected by Harness
        ports:
        - containerPort: 5000
