# deployment-template.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app # Harness will append -blue or -green suffixes internally
  labels:
    app: python-app
    
    # Harness will inject harness.io/color: blue or harness.io/color: green onto the pods
spec:
  replicas: 4 # Number of replicas for your environment
  selector:
    matchLabels:
      app: python-app
      harness.io/track: stable
      # Harness will automatically match on harness.io/color for traffic routing
  template:
    metadata:
      labels:
        app: python-app
        harness.io/track: stable
        # Harness will inject harness.io/color: blue or harness.io/color: green here
    spec:
      containers:
      - name: python-app
        image: "{{ .Values.image }}" # Image will be injected by Harness from app-values.yaml
        ports:
        - containerPort: 5000
