# deployment-template.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  # The name will be dynamically set by Harness, e.g., python-app-blue or python-app-green
  # The entire string including the template must be quoted
  name: "python-app-{{ .Values.versionLabel }}"
  labels:
    app: python-app
    # The entire string including the template must be quoted
    version: "{{ .Values.versionLabel }}"
spec:
  replicas: 4 # Number of replicas for your environment
  selector:
    matchLabels:
      app: python-app
      # The entire string including the template must be quoted
      version: "{{ .Values.versionLabel }}"
  template:
    metadata:
      labels:
        app: python-app
        # The entire string including the template must be quoted
        version: "{{ .Values.versionLabel }}"
    spec:
      containers:
      - name: python-app
        # The entire string including the template must be quoted
        image: "{{ .Values.image }}"
        ports:
        - containerPort: 5000
