# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: python-app-service # Stable service name
  labels:
    app: python-app
spec:
  selector:
    app: python-app # <--- REMOVE: harness.io/color: "blue" here
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      name: http # Important for Istio!
  type: LoadBalancer # Or ClusterIP, NodePort, depending on your needs
